# Generated by Django 5.2.8 on 2025-12-27 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smsapp", "0003_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="smsapp.course"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="session_year_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="smsapp.session_year"
            ),
        ),
    ]
