# Generated by Django 5.2.8 on 2025-12-27 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smsapp", "0005_alter_student_updated_at_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch_Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_start", models.CharField(max_length=100)),
                ("batch_end", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="session_year_id",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "HOD"), (2, "STAFF"), (3, "STUDENT")],
                default=1,
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="batch_year_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="smsapp.batch_year",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Session_Year",
        ),
    ]
