# Generated by Django 5.2.8 on 2025-12-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smsapp", "0007_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
