# Generated by Django 5.2.8 on 2025-12-29 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smsapp", "0008_alter_subject_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
