# Generated by Django 5.2.8 on 2025-12-30 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smsapp", "0009_alter_subject_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff_Notificatioon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="smsapp.staff"
                    ),
                ),
            ],
        ),
    ]
