# Generated by Django 5.2.8 on 2025-12-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smsapp", "0010_staff_notificatioon"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Staff_Notificatioon",
            new_name="Staff_Notification",
        ),
    ]
