# Generated by Django 5.2.8 on 2025-12-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smsapp", "0011_rename_staff_notificatioon_staff_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_notification",
            name="status",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
