# Generated by Django 5.2.8 on 2026-01-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smsapp", "0016_student_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff_feedback",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student_feedback",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
